In [ ]:
import numpy as np

#Numpy Operations

1.	Create NumPy Arrays

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2.	Inspection and Properties

Inspect the shape of the temperatures_w1 array

In [ ]:
temperatures_w1.shape

(7,)

Determine the data type of the temperatures_w1 array elements.



In [ ]:
temperatures_w1.dtype

dtype('float64')

Find out the number of elements in the temperatures_w1 array.

In [ ]:
temperatures_w1.size

7

3.	Array Operations

Convert the temperatures_w1 from Celsius to Fahrenheit

In [ ]:
Fahrenheit = (temperatures_w1 * 9/5) + 32
print(Fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


Find the maximum and minimum temperatures of the week.



In [ ]:
np.max(temperatures_w1)

np.float64(26.1)

In [ ]:
np.min(temperatures_w1)

np.float64(20.8)

Calculate the mean (average) temperature of the week.

In [ ]:
np.mean(temperatures_w1)

np.float64(23.542857142857144)

4.	Array Slicing and Indexing

Extract the temperatures for the first three days of the week.

In [ ]:
temperatures_w1[:3]

array([22.5, 25.3, 20.8])

Extract the temperatures for the weekend (last two days).

In [ ]:
temperatures_w1[-2:]

array([24.8, 21.9])

Extract the temperatures for the middle three days of the week

In [ ]:
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

5.	Create a 2D Array

In [ ]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] ])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6.	Inspect and Slice the 2D Array

Inspect and print the shape, data type, and total number of elements in the temperatures array

In [ ]:
temperatures.shape

(2, 7)

In [ ]:
temperatures.dtype

dtype('float64')

In [ ]:
temperatures.size

14

The temperatures for the first week (Row 1).

In [ ]:
temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

The temperatures for the second week (Row 2).

In [ ]:
temperatures[1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

The temperatures for the first three days of each week.

In [ ]:
temperatures[:3, :3]

array([[22.5, 25.3, 20.8],
       [19.2, 22.5, 21.3]])

The temperatures for the weekends (last two days) of both weeks.

In [ ]:
temperatures[-2:, -2:]

array([[24.8, 21.9],
       [22.8, 20.1]])